-- =====================================================
-- Spring Batch 메타데이터 테이블 (Oracle)
-- =====================================================

-- 1. 시퀀스 생성
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE NOCACHE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ  START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE NOCACHE;
CREATE SEQUENCE BATCH_JOB_SEQ            START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE NOCACHE;

-- =====================================================
-- 2. 테이블 생성
-- =====================================================

-- 잡 인스턴스: 동일한 잡 이름 + 파라미터 조합의 논리적 실행 단위
CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID NUMBER(19,0)  NOT NULL PRIMARY KEY,
    VERSION         NUMBER(19,0),
    JOB_NAME        VARCHAR2(100) NOT NULL,
    JOB_KEY         VARCHAR2(32)  NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

COMMENT ON TABLE  BATCH_JOB_INSTANCE                IS 'Spring Batch 잡 인스턴스 - 동일한 잡 이름과 파라미터 조합의 논리적 실행 단위';
COMMENT ON COLUMN BATCH_JOB_INSTANCE.JOB_INSTANCE_ID IS '잡 인스턴스 고유 ID (시퀀스 BATCH_JOB_SEQ 사용)';
COMMENT ON COLUMN BATCH_JOB_INSTANCE.VERSION         IS '낙관적 락(Optimistic Lock)을 위한 버전 번호';
COMMENT ON COLUMN BATCH_JOB_INSTANCE.JOB_NAME        IS '잡 이름 (JobBuilder에 지정한 이름)';
COMMENT ON COLUMN BATCH_JOB_INSTANCE.JOB_KEY         IS '잡 파라미터를 직렬화한 MD5 해시값 (동일 파라미터 중복 실행 방지)';


-- 잡 실행: 잡 인스턴스의 실제 실행 이력 (1 인스턴스 : N 실행)
CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID NUMBER(19,0)  NOT NULL PRIMARY KEY,
    VERSION          NUMBER(19,0),
    JOB_INSTANCE_ID  NUMBER(19,0)  NOT NULL,
    CREATE_TIME      TIMESTAMP     NOT NULL,
    START_TIME       TIMESTAMP     DEFAULT NULL,
    END_TIME         TIMESTAMP     DEFAULT NULL,
    STATUS           VARCHAR2(10),
    EXIT_CODE        VARCHAR2(2500),
    EXIT_MESSAGE     VARCHAR2(2500),
    LAST_UPDATED     TIMESTAMP,
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

COMMENT ON TABLE  BATCH_JOB_EXECUTION                  IS 'Spring Batch 잡 실행 이력 - 잡 인스턴스의 실제 실행 기록 (1 인스턴스 : N 실행)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION.JOB_EXECUTION_ID IS '잡 실행 고유 ID (시퀀스 BATCH_JOB_EXECUTION_SEQ 사용)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION.VERSION          IS '낙관적 락을 위한 버전 번호';
COMMENT ON COLUMN BATCH_JOB_EXECUTION.JOB_INSTANCE_ID  IS '연관된 잡 인스턴스 ID (FK)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION.CREATE_TIME       IS '실행 레코드 생성 시각';
COMMENT ON COLUMN BATCH_JOB_EXECUTION.START_TIME        IS '잡 실행 시작 시각';
COMMENT ON COLUMN BATCH_JOB_EXECUTION.END_TIME          IS '잡 실행 종료 시각 (성공/실패 무관)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION.STATUS            IS '실행 상태 (COMPLETED, FAILED, STOPPED, STARTING 등)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION.EXIT_CODE         IS '종료 코드 (COMPLETED, FAILED 등 - 재시작 여부 판단에 사용)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION.EXIT_MESSAGE      IS '종료 메시지 또는 예외 스택트레이스 (최대 2500자)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION.LAST_UPDATED      IS '마지막 상태 갱신 시각';


-- 잡 실행 파라미터: 잡 실행 시 전달된 파라미터 저장
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID NUMBER(19,0)  NOT NULL,
    TYPE_CD          VARCHAR2(6)   NOT NULL,
    KEY_NAME         VARCHAR2(100) NOT NULL,
    STRING_VAL       VARCHAR2(250),
    DATE_VAL         TIMESTAMP     DEFAULT NULL,
    LONG_VAL         NUMBER(19,0),
    DOUBLE_VAL       NUMBER(*,5),
    IDENTIFYING      CHAR(1)       NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

COMMENT ON TABLE  BATCH_JOB_EXECUTION_PARAMS                  IS 'Spring Batch 잡 실행 파라미터 - 잡 실행 시 전달된 파라미터를 타입별로 저장';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID IS '연관된 잡 실행 ID (FK)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS.TYPE_CD          IS '파라미터 타입 코드 (STRING, DATE, LONG, DOUBLE)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS.KEY_NAME         IS '파라미터 키 이름';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS.STRING_VAL       IS '문자열 타입 파라미터 값';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS.DATE_VAL         IS '날짜 타입 파라미터 값';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS.LONG_VAL         IS '정수(Long) 타입 파라미터 값';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS.DOUBLE_VAL       IS '실수(Double) 타입 파라미터 값';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_PARAMS.IDENTIFYING      IS 'JOB_KEY 해시 포함 여부 (Y: 인스턴스 식별에 사용, N: 참고용)';


-- 스텝 실행: 잡 내 각 스텝의 실행 이력 및 처리 건수 통계
CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID  NUMBER(19,0)  NOT NULL PRIMARY KEY,
    VERSION            NUMBER(19,0)  NOT NULL,
    STEP_NAME          VARCHAR2(100) NOT NULL,
    JOB_EXECUTION_ID   NUMBER(19,0)  NOT NULL,
    START_TIME         TIMESTAMP     NOT NULL,
    END_TIME           TIMESTAMP     DEFAULT NULL,
    STATUS             VARCHAR2(10),
    COMMIT_COUNT       NUMBER(19,0),
    READ_COUNT         NUMBER(19,0),
    FILTER_COUNT       NUMBER(19,0),
    WRITE_COUNT        NUMBER(19,0),
    READ_SKIP_COUNT    NUMBER(19,0),
    WRITE_SKIP_COUNT   NUMBER(19,0),
    PROCESS_SKIP_COUNT NUMBER(19,0),
    ROLLBACK_COUNT     NUMBER(19,0),
    EXIT_CODE          VARCHAR2(2500),
    EXIT_MESSAGE       VARCHAR2(2500),
    LAST_UPDATED       TIMESTAMP,
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

COMMENT ON TABLE  BATCH_STEP_EXECUTION                    IS 'Spring Batch 스텝 실행 이력 - 잡 내 각 스텝의 실행 기록 및 처리 건수 통계';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.STEP_EXECUTION_ID  IS '스텝 실행 고유 ID (시퀀스 BATCH_STEP_EXECUTION_SEQ 사용)';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.VERSION            IS '낙관적 락을 위한 버전 번호 (스텝 진행 중 주기적으로 증가)';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.STEP_NAME          IS '스텝 이름 (StepBuilder에 지정한 이름)';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.JOB_EXECUTION_ID   IS '연관된 잡 실행 ID (FK)';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.START_TIME         IS '스텝 실행 시작 시각';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.END_TIME           IS '스텝 실행 종료 시각';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.STATUS             IS '실행 상태 (COMPLETED, FAILED, STOPPED 등)';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.COMMIT_COUNT       IS '청크(Chunk) 커밋 횟수';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.READ_COUNT         IS 'ItemReader가 읽은 총 건수';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.FILTER_COUNT       IS 'ItemProcessor에서 필터링(null 반환)된 건수';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.WRITE_COUNT        IS 'ItemWriter가 기록한 총 건수';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.READ_SKIP_COUNT    IS '읽기 단계에서 스킵된 건수';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.WRITE_SKIP_COUNT   IS '쓰기 단계에서 스킵된 건수';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.PROCESS_SKIP_COUNT IS '처리 단계에서 스킵된 건수';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.ROLLBACK_COUNT     IS '롤백 횟수 (스킵으로 인한 롤백 포함)';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.EXIT_CODE          IS '종료 코드';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.EXIT_MESSAGE       IS '종료 메시지 또는 예외 스택트레이스 (최대 2500자)';
COMMENT ON COLUMN BATCH_STEP_EXECUTION.LAST_UPDATED       IS '마지막 상태 갱신 시각';


-- 스텝 실행 컨텍스트: 스텝 재시작을 위한 상태 저장소 (ExecutionContext)
CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID  NUMBER(19,0)  NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR2(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

COMMENT ON TABLE  BATCH_STEP_EXECUTION_CONTEXT                    IS 'Spring Batch 스텝 실행 컨텍스트 - 재시작 시 복원을 위한 스텝 상태 저장소 (ExecutionContext 직렬화)';
COMMENT ON COLUMN BATCH_STEP_EXECUTION_CONTEXT.STEP_EXECUTION_ID  IS '연관된 스텝 실행 ID (FK, PK 겸용)';
COMMENT ON COLUMN BATCH_STEP_EXECUTION_CONTEXT.SHORT_CONTEXT      IS '직렬화된 컨텍스트 요약 (2500자 이하 시 전체 저장)';
COMMENT ON COLUMN BATCH_STEP_EXECUTION_CONTEXT.SERIALIZED_CONTEXT IS '2500자 초과 시 전체 직렬화 데이터를 CLOB으로 저장';


-- 잡 실행 컨텍스트: 잡 재시작을 위한 상태 저장소 (ExecutionContext)
CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID   NUMBER(19,0)  NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR2(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

COMMENT ON TABLE  BATCH_JOB_EXECUTION_CONTEXT                   IS 'Spring Batch 잡 실행 컨텍스트 - 재시작 시 복원을 위한 잡 레벨 상태 저장소 (ExecutionContext 직렬화)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID  IS '연관된 잡 실행 ID (FK, PK 겸용)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT     IS '직렬화된 컨텍스트 요약 (2500자 이하 시 전체 저장)';
COMMENT ON COLUMN BATCH_JOB_EXECUTION_CONTEXT.SERIALIZED_CONTEXT IS '2500자 초과 시 전체 직렬화 데이터를 CLOB으로 저장';