# ?? ?? ???
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime) | %(executionTime)ms | %(sql)
# ?? ??
sqlExpression=true

# ?? ?? ?? (??)
appender=com.p6spy.engine.spy.appender.Slf4JLogger
slf4jLogLevel=INFO
loggerCategory=p6spy

# ?? ?? ?? (ms)
outagedetection=true
outagedetectioninterval=2